/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/Authentication/AuthenticateSLGUser": {
    post: {
      parameters: {
        query: {
          username?: string;
          password?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["AuthenticationResult"];
            "application/json": components["schemas"]["AuthenticationResult"];
            "text/json": components["schemas"]["AuthenticationResult"];
          };
        };
      };
    };
  };
  "/Authentication/AuthenticateSteamUser": {
    post: {
      parameters: {
        query: {
          steamTicket?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["AuthenticationResult"];
            "application/json": components["schemas"]["AuthenticationResult"];
            "text/json": components["schemas"]["AuthenticationResult"];
          };
        };
      };
    };
  };
  "/Authentication/GetWorldTicket": {
    get: {
      parameters: {
        query: {
          serverId?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": string;
            "application/json": string;
            "text/json": string;
          };
        };
      };
    };
  };
  "/Authentication/VerifyWorldTicket": {
    get: {
      parameters: {
        query: {
          worldTicket?: string;
          expectedWorldId?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StrangeUser"];
            "application/json": components["schemas"]["StrangeUser"];
            "text/json": components["schemas"]["StrangeUser"];
          };
        };
      };
    };
  };
  "/Flags/FlagServer": {
    post: {
      parameters: {
        query: {
          worldTicket?: string;
          problemDescription?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Flags": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    put: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["FlagReported"];
        };
      };
    };
  };
  "/Flags/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["FlagReported"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Flags/search": {
    get: {
      parameters: {
        query: {
          search: string;
          pageNumber?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["FlagReported"][];
          };
        };
      };
    };
  };
  "/Marketplace/GetMarketplaceItems": {
    get: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["MarketplaceItem"][];
            "application/json": components["schemas"]["MarketplaceItem"][];
            "text/json": components["schemas"]["MarketplaceItem"][];
          };
        };
      };
    };
  };
  "/Marketplace/PutStoreItemsAdmin": {
    post: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
  "/Marketplace/BuyAsAdmin": {
    post: {
      parameters: {
        query: {
          marketplaceItemName?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Marketplace/StartStorePurchase": {
    post: {
      parameters: {
        query: {
          marketplaceItemName?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["MarketplaceTransaction"];
            "application/json": components["schemas"]["MarketplaceTransaction"];
            "text/json": components["schemas"]["MarketplaceTransaction"];
          };
        };
      };
    };
  };
  "/Marketplace/CompleteStorePurchase": {
    post: {
      parameters: {
        query: {
          transactionId?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": boolean;
            "application/json": boolean;
            "text/json": boolean;
          };
        };
      };
    };
  };
  "/PasswordReset/RequestReset": {
    post: {
      parameters: {
        query: {
          email?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/PasswordReset/ResetPassword": {
    post: {
      parameters: {
        query: {
          token?: string;
          newpassword?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/Registration/SetUsernameAndPassword": {
    post: {
      parameters: {
        query: {
          userName?: string;
          email?: string;
          password?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/Registration/RegisterUser": {
    post: {
      parameters: {
        query: {
          username?: string;
          email?: string;
          password?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["AuthenticationResult"];
            "application/json": components["schemas"]["AuthenticationResult"];
            "text/json": components["schemas"]["AuthenticationResult"];
          };
        };
      };
    };
  };
  "/api/Registration/VerifyEmail": {
    post: {
      parameters: {
        query: {
          verifyToken?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/Registration/LinkSteamAccount": {
    /** Details about Steam's OAuth flow can be found here https://partner.steamgames.com/doc/webapi_overview/oauth. */
    post: {
      parameters: {
        query: {
          token?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/Registration/RegisterWithSteam": {
    get: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Transactions": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    put: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["MarketplaceTransaction"];
        };
      };
    };
  };
  "/Transactions/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["MarketplaceTransaction"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Transactions/search": {
    get: {
      parameters: {
        query: {
          search: string;
          pageNumber?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["MarketplaceTransaction"][];
          };
        };
      };
    };
  };
  "/UserAccount/SetAccount": {
    get: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StrangeUser"];
          "text/json": components["schemas"]["StrangeUser"];
          "application/*+json": components["schemas"]["StrangeUser"];
        };
      };
    };
  };
  "/UserAccount/GetAccount": {
    get: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StrangeUser"];
            "application/json": components["schemas"]["StrangeUser"];
            "text/json": components["schemas"]["StrangeUser"];
          };
        };
      };
    };
  };
  "/UserAccount/SetAvatarData": {
    post: {
      parameters: {
        query: {
          avatarDna?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/UserAccount/GetUserSteamStatus": {
    get: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": string;
            "application/json": string;
            "text/json": string;
          };
        };
      };
    };
  };
  "/UserAccount/GetTransactionSummaries": {
    get: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["DailySummary"][];
            "application/json": components["schemas"]["DailySummary"][];
            "text/json": components["schemas"]["DailySummary"][];
          };
        };
      };
    };
  };
  "/UserAccount/GetAllTransactionSummaries": {
    get: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["DailySummary"][];
            "application/json": components["schemas"]["DailySummary"][];
            "text/json": components["schemas"]["DailySummary"][];
          };
        };
      };
    };
  };
  "/UserAccount/GrantAchievements": {
    post: {
      parameters: {
        query: {
          userId?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StrangeAchievement"][];
          "text/json": components["schemas"]["StrangeAchievement"][];
          "application/*+json": components["schemas"]["StrangeAchievement"][];
        };
      };
    };
  };
  "/UserAccount/GrantAchievement": {
    post: {
      parameters: {
        query: {
          userId?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StrangeAchievement"];
          "text/json": components["schemas"]["StrangeAchievement"];
          "application/*+json": components["schemas"]["StrangeAchievement"];
        };
      };
    };
  };
  "/UserAccount/Heartbeat": {
    post: {
      parameters: {
        query: {
          worldId?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["HearbeatResult"];
            "application/json": components["schemas"]["HearbeatResult"];
            "text/json": components["schemas"]["HearbeatResult"];
          };
        };
      };
    };
  };
  "/UserAccount": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    put: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StrangeUser"];
        };
      };
    };
  };
  "/UserAccount/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["StrangeUser"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/UserAccount/search": {
    get: {
      parameters: {
        query: {
          search: string;
          pageNumber?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["StrangeUser"][];
          };
        };
      };
    };
  };
  "/Voice/VivoxLoginToken": {
    post: {
      parameters: {
        query: {
          vivoxId?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["VoiceLoginTokenResult"];
            "application/json": components["schemas"]["VoiceLoginTokenResult"];
            "text/json": components["schemas"]["VoiceLoginTokenResult"];
          };
        };
      };
    };
  };
  "/Voice/VivoxJoinChannelToken": {
    post: {
      parameters: {
        query: {
          vivoxId?: string;
          channelName?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["VoiceJoinTokenResult"];
            "application/json": components["schemas"]["VoiceJoinTokenResult"];
            "text/json": components["schemas"]["VoiceJoinTokenResult"];
          };
        };
      };
    };
  };
  "/Worlds/GetWorld": {
    get: {
      parameters: {
        query: {
          id?: string;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StrangeWorldCloudData"];
            "application/json": components["schemas"]["StrangeWorldCloudData"];
            "text/json": components["schemas"]["StrangeWorldCloudData"];
          };
        };
      };
    };
  };
  "/Worlds/GetActiveWorlds": {
    get: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StrangeWorldCloudData"][];
            "application/json": components["schemas"]["StrangeWorldCloudData"][];
            "text/json": components["schemas"]["StrangeWorldCloudData"][];
          };
        };
      };
    };
  };
  "/Worlds/QuickUpdate": {
    post: {
      parameters: {
        query: {
          playerCount?: number;
          activePlayerCount?: number;
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": string;
          "text/json": string;
          "application/*+json": string;
        };
      };
    };
  };
  "/Worlds/Test": {
    post: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StrangeWorldCloudData"];
          "text/json": components["schemas"]["StrangeWorldCloudData"];
          "application/*+json": components["schemas"]["StrangeWorldCloudData"];
        };
      };
    };
  };
  "/Worlds/Test4": {
    post: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StrangeWorldCloudData"];
          "text/json": components["schemas"]["StrangeWorldCloudData"];
          "application/*+json": components["schemas"]["StrangeWorldCloudData"];
        };
      };
    };
  };
  "/Worlds/AddOrUpdate": {
    post: {
      parameters: {
        query: {
          "api-version"?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StrangeWorldCloudData"];
          "text/json": components["schemas"]["StrangeWorldCloudData"];
          "application/*+json": components["schemas"]["StrangeWorldCloudData"];
        };
      };
    };
  };
  "/Worlds": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    put: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["StrangeWorldCloudData"];
        };
      };
    };
  };
  "/Worlds/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["StrangeWorldCloudData"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Worlds/search": {
    get: {
      parameters: {
        query: {
          search: string;
          pageNumber?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["StrangeWorldCloudData"][];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    AuthenticationResult: {
      token?: string | null;
      strangeUser?: components["schemas"]["StrangeUser"];
    };
    DailySummary: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      userID?: string | null;
      /** Format: date */
      date?: string;
      /** Format: float */
      totalCollected?: number;
    };
    /** @description Info stored about a server in the cloud stroage db */
    FlagReported: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      reportTime?: string;
      reportingUserID?: string | null;
      problemDescription?: string | null;
      reportedWorldID?: string | null;
      reportedUserID?: string | null;
    };
    HearbeatResult: {
      success?: boolean;
      reason?: string | null;
    };
    InvItem: {
      type?: string | null;
      /** Format: int32 */
      amount?: number;
      /** Format: uuid */
      serverBoughtOn?: string;
      /** Format: uuid */
      owningUserOfServerBoughtOn?: string;
    };
    MarketplaceItem: {
      entryName?: string | null;
      type?: string | null;
      displayName?: string | null;
      achievementRequired?: string | null;
      category?: string | null;
      /** Format: int32 */
      quantity?: number;
      /** Format: float */
      price?: number;
      realMoney?: boolean;
      /** Format: int32 */
      steamID?: number;
    };
    MarketplaceTransaction: {
      /** Format: uuid */
      id?: string;
      marketplaceItemName?: string | null;
      displayName?: string | null;
      steamOrderId?: string | null;
      steamTransactionId?: string | null;
      /** Format: uuid */
      purchaser?: string;
      purchaserSteamId?: string | null;
      /** Format: uuid */
      worldPurchasedOn?: string | null;
      /** Format: uuid */
      worldOwningUser?: string | null;
      /** Format: int32 */
      quantity?: number;
      /** Format: float */
      spentTotal?: number;
      /** Format: float */
      slgReceived?: number;
      /** Format: float */
      worldOwnerReceived?: number;
      realMoney?: boolean;
      badTransaction?: boolean;
      completed?: boolean;
      /** Format: date-time */
      timeCompleted?: string;
    };
    StrangeAchievement: {
      name?: string | null;
      /** Format: uuid */
      worldSource?: string;
      worldName?: string | null;
      description?: string | null;
      /** Format: date-time */
      timeAchieved?: string | null;
    };
    /** @description A user stored in the StrangeCloud. */
    StrangeUser: {
      /** Format: uuid */
      id?: string;
      steamId?: string | null;
      twitchId?: string | null;
      twitchUsername?: string | null;
      username?: string | null;
      avatarUrl?: string | null;
      avatarDna?: string | null;
      achievements?: components["schemas"]["StrangeAchievement"][] | null;
      /** Format: float */
      ecoCredits?: number;
      ownsEco?: boolean;
      verified?: boolean;
      items?: components["schemas"]["InvItem"][] | null;
      blockPurchasing?: boolean | null;
      isDeveloper?: boolean;
      isCloudAdmin?: boolean;
      /** Format: date-time */
      bannedUntil?: string | null;
      bannedReason?: string | null;
      isBanned?: boolean;
      /** Format: uuid */
      lastWorldId?: string | null;
      /** Format: date-time */
      lastWorldJoinTime?: string | null;
      /** Format: date-time */
      heartBeatTime?: string | null;
      /** Format: date-time */
      creationTime?: string;
      online?: boolean;
      timeOnlineTotal?: components["schemas"]["TimeSpan"];
      /** Format: date-time */
      lastEmailSent?: string | null;
    };
    /** @description Info stored about a server in the cloud stroage db */
    StrangeWorldCloudData: {
      /** Format: uuid */
      id?: string;
      name?: string | null;
      /** Format: uuid */
      owningUser?: string;
      /** Format: int32 */
      gameServerPort?: number;
      internalEndPoint?: string | null;
      remoteEndPoint?: string | null;
      isPublic?: boolean;
      /** Format: int32 */
      playerCount?: number;
      /** Format: int32 */
      activePlayerCount?: number;
      serverInfoJson?: string | null;
      online?: boolean;
      isOfficial?: boolean | null;
    };
    TimeSpan: {
      /** Format: int64 */
      ticks?: number;
      /** Format: int32 */
      days?: number;
      /** Format: int32 */
      hours?: number;
      /** Format: int32 */
      milliseconds?: number;
      /** Format: int32 */
      microseconds?: number;
      /** Format: int32 */
      nanoseconds?: number;
      /** Format: int32 */
      minutes?: number;
      /** Format: int32 */
      seconds?: number;
      /** Format: double */
      totalDays?: number;
      /** Format: double */
      totalHours?: number;
      /** Format: double */
      totalMilliseconds?: number;
      /** Format: double */
      totalMicroseconds?: number;
      /** Format: double */
      totalNanoseconds?: number;
      /** Format: double */
      totalMinutes?: number;
      /** Format: double */
      totalSeconds?: number;
    };
    /** @description Response for channel join request */
    VoiceJoinTokenResult: {
      token?: string | null;
      channelId?: string | null;
    };
    /** @description Vivox login result, and info needed for vivox client */
    VoiceLoginTokenResult: {
      token?: string | null;
      accountId?: string | null;
      server?: string | null;
    };
  };
}

export interface operations {}

export interface external {}
