import { createLazyFileRoute } from '@tanstack/react-router'

export const Route = createLazyFileRoute('/terms/eula')({
  component:  Eula
})

export function Eula() {
  return (
    <section className='page-wrap-main d-flex col-lg-offset-2 col-lg-8 justify-content-center'>
    <div className="col-md-12">
    <section className="row first-section">
	<div className="col-md-12">
		<article className="">
			<div className="feature-box">
				<h2 className="account-title">End-user license agreement</h2>
				<div>
					<p dir="ltr">This End User License Agreement (&ldquo;License&rdquo;) is an agreement between you and Strange Loop Games Inc and its affiliates (collectively &quot;SLG&quot;). This License governs your use of legitimate copies of ECO, and all related documentation, utilities, and updates and upgrades that replace or supplement the software and are not distributed with a separate license (collectively, the &quot;Software&quot;).  This Software is licensed to you, not sold. By installing or using the Software, you agree to accept the terms and conditions of this License and be bound to them.  If you do not agree to the terms of this License, then do not install or use the Software. Sections 3 and 4 below describe data SLG may use to provide services and support to you in connection with the Software.  If you do not agree to this use of data, do not install or use the Software. IF YOU INSTALL the Software, you fully accept the terms and conditions of this License.  By placing an order on SLG, you agree that you are submitting a binding offer to purchase digital content, such as digital versions of SLG games and digital content for SLG (“Digital Content”) or service from SLG. YOU HEREBY EXPRESSLY AGREE THAT THE SUPPLY OF DIGITAL CONTENT AND THE PERFORMANCE OF SLG' SERVICES BEGINS IMMEDIATELY AFTER PURCHASE IS SENT. YOU ALSO ACKNOWLEDGE THAT SLG RESERVES THE RIGHTS TO TERMINATE YOUR ACCESS TO ANY GAMES, PRODUCTS OR CONTENT PROVIDED BY US TO YOU IN CASE OF A CLAIM SUBMITTED AGAINST SLG. No refunds are permitted.  </p>
					<p dir="ltr"> </p>
					<p dir="ltr">1. Limited License Grant and Terms   </p>
					<br />
					<p dir="ltr"> &nbsp;&nbsp;&nbsp;A.  Grant. Through an authorized purchase, you acquire and SLG grants you a non-exclusive license to install and use the Software for your personal, limited, non commercial use solely as set forth in this License. Your acquired rights are subject to your agreement and continuing compliance with this License. Commercial use of the Software is prohibited. You are expressly prohibited from sublicensing, renting, leasing or otherwise distributing the Software or rights to use the Software. Your License term begins on the date on which you install or otherwise use the Software, and ends on the date that you dispose of the Software or SLG terminates this License, whichever is earlier.  Your license will terminate immediately if you attempt to circumvent the technical protection measures for the Software.  All use of the Software is subject to this License. </p>
					<br />
					<p dir="ltr"> B.  Technical Protection Measures.  Your license to the Software is verified by logging into and authorizing your account with your copy of the Software.  If you disable or otherwise tamper with the technical protection measures, the Software may not function properly and you will have materially breached this License.  </p>
					<br />
					<br />
					<p dir="ltr">2.  Intellectual Property Rights and Ownership.</p>
					<br />
					<p dir="ltr"> &nbsp;&nbsp;&nbsp;A.  Reservation of Rights: &nbsp;</p>
					<p dir="ltr"> &nbsp;&nbsp;&nbsp;You have purchased a limited license to the Software and your rights are limited to the license grant above and subject to this License.  You may not otherwise copy, display, distribute, perform, publish, modify, or use the Software or any component of it.  You are prohibited from making a copy of the Software available on a network where it could be used or downloaded by multiple users. Except as expressly licensed to you herein, SLG and its licensors, as applicable, owns and reserves all right, title and interest in the Software, and all related data, characters, themes, objects, storyline, images, photographs, graphics, animations, video, music, text, and the associated copyrights, trademarks, moral rights and other intellectual property rights therein.  This License is limited to the intellectual property rights of SLG and its licensors in the Software and does not include any rights to other patents or intellectual property. Except to the extent permitted under applicable law, you may not decompile, disassemble, reverse engineer or create derivative works of the Software by any means whatsoever. You may not remove, alter, or obscure any product identification, copyright, or other intellectual property notices in the Software. All rights not expressly granted herein are reserved to SLG.</p>
					<br />
					<p dir="ltr"> &nbsp;&nbsp;&nbsp;B.  Contributing Content:</p>
					<p dir="ltr"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.  You may not upload any content that adds to or modifies or manages the Software that is protected by copyright, trademark or other intellectual property rights unless you are permitted to do so by the owner or law.  SLG may, without prior notice to you and in its sole judgment, remove content that may infringe the intellectual property rights of a third party.  If you infringe on SLG's, or a third party&rsquo;s intellectual property rights, SLG may terminate your SLG account without notice to you.   </p>
					<p dir="ltr"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. &nbsp;Any contribution of content, when you contribute content to the Software, you expressly grant to SLG a non-exclusive, perpetual, fully transferable and sub-licensable, worldwide, irrevocable right to use, reproduce, modify and create derivative works from, distribute, transmit, broadcast, and publicly display and perform the content, or any portion thereof, in connection with the distribution of such content to other users and potential users of the Software (such as, for example, featuring such content for download, and in the marketing and advertising of the Software, without further notice, payment, or attribution to you. You grant SLG all licenses, consents and clearances to enable SLG to use such content for such purposes</p>
					<br />
					<p dir="ltr">3.  Consent to Collection and Use of Data:  To facilitate the provision of software updates; dynamically served content including advertising; product support; and online services to you, you agree that SLG and its affiliates may collect, use, store, and transmit technical and related information that identifies your computer (such as Internet Protocol Address and hardware identification), operating system, and application software and peripheral hardware, and non-personally identifiable gameplay and software usage statistics, without further notice to you.  SLG and its affiliates may also use this information in the aggregate, in a form which does not personally identify you, to improve our products and services and we may share anonymous aggregate data with our third party service providers. </p>
					<br />
					<p dir="ltr">4. &nbsp;Consent to Public Display of Data: SLG and its affiliates may also collect, use, store, transmit and publicly display data regarding your content contributions, and associate you with content that is created and shared by you with other players and SLG. Data that personally identifies you is collected, used, stored and transmitted in accordance with SLG Privacy Policy</p>
					<br />
					<p dir="ltr">5. &nbsp;Termination: This License is effective until terminated. Your rights under this License will terminate immediately and automatically without any notice from SLG if you fail to comply with any of the terms and conditions of this License. Promptly upon termination, you must cease all use of the Software and destroy all copies of the Software in your possession or control.  Termination will not limit any of SLG&rsquo;s other rights or remedies at law or in equity. Sections 2 and 4 of this License shall survive termination or expiration of this License for any reason.  </p>
					<br />
					<p dir="ltr">6. &nbsp;Limitation of Liability: To the fullest extent permissible by applicable law, in no event shall SLG, its subsidiaries or its affiliates be liable to you for any loss or damage of any kind arising out of, relating to, or in connection with this license or the software, including without limitation personal injury, property damage, loss of data (including player characters, virtual goods or currency, accounts, statistics, or other user data), loss of goodwill, interruption of service, work stoppage, computer disruption, interference, failure or malfunction, lost profits, cost of substitute goods or services, or any form of indirect, special, incidental, consequential or punitive damages, whether such alleged loss or damage arises in tort (including negligence), contract, strict liability or otherwise, and whether or not SLG has been advised of the possibility of such damage. Some jurisdictions do not allow a limitation of liability for death, personal injury, fraudulent misrepresentations or certain intentional or negligent acts, or violation of specific statutes, or the limitation of incidental or consequential damages, so some or all of the above limitations of liability may not apply to you. In no event shall SLG&rsquo;s total liability to you for all damages (except as required by applicable law) exceed the amount actually paid by you for the software.  </p>
					<br />
					<p dir="ltr">7. &nbsp;Limitation of Liability and Disclaimer of Warranties are Material Terms of this License: You agree that the provisions in this License that limit liability are essential terms of this License.  </p>
					<br />
					<p dir="ltr">8. &nbsp;Severability and Survival: If any provision of this License is illegal or unenforceable under applicable law, the remainder of the provision shall be amended to achieve as closely as possible the effect of the original term and all other provisions of this License shall continue in full force and effect.</p>
					<br />
					<p dir="ltr">9. &nbsp;U.S. Government Restricted Rights: If you are a government end user, then this provision applies to you.  The Software is provided as &ldquo;commercial items,&rdquo; &ldquo;commercial computer software&rdquo; and/or &ldquo;commercial computer software documentation.&rdquo;  Consistent with DFARS section 227.7202 and FAR section 12.212, and to the extent required under U.S. federal law, the minimum restricted rights as set forth in FAR section 52.227‐19 (or any equivalent or subsequent agency regulation thereof), any use, modification, reproduction, release, performance, display, disclosure or distribution thereof by or for the U.S. Government shall be governed solely by this License and shall be prohibited except to the extent expressly permitted by this License.</p>
					<br />
					<p dir="ltr">10. &nbsp;Injunctive Relief: You agree that a breach of this License may cause irreparable injury to SLG for which monetary damages would not be an adequate remedy and SLG shall be entitled to seek equitable relief in addition to any remedies it may have hereunder or at law.</p>
					<br />
					<p dir="ltr">11. &nbsp; Governing Law. This License shall be governed by and construed (without regard to conflicts or choice of law principles) under the laws of the State of Washington as applied to agreements entered into and to be performed entirely in Washington between Washington residents. Unless expressly waived by SLG in writing for the particular instance or contrary to local law, the sole and exclusive jurisdiction and venue for actions related to the subject matter hereof shall be the Washington state and federal courts having within their jurisdiction the location of SLG&rsquo;s principal corporate place of business.  Both parties consent to the jurisdiction of such courts and agree that process may be served in the manner provided herein for giving of notices or otherwise as allowed by Washington or federal law.  The parties agree that the UN Convention on Contracts for the International Sale of Goods (Vienna, 1980) shall not apply to this License or to any dispute or transaction arising out of this License.</p>
					<br />
					<p dir="ltr">12. &nbsp;Export: You agree to abide by U.S. and other applicable export control laws and agree not to transfer the Software to a foreign national, or national destination, which is prohibited by such laws, without first obtaining, and then complying with, any requisite government authorization. You certify that you are not a person with whom SLG is prohibited from transacting business under applicable law.</p>
					<br />
					<p dir="ltr">13. &nbsp;Third Party Technology:    If you use this Software on a MAC, then your Software incorporates technology developed by TransGaming Inc. (&ldquo;Cider&rdquo;). Cider(tm) is Copyright © 2000-2009 TransGaming Inc.</p>
					<br />
					<p dir="ltr">14. &nbsp;  Entire Agreement:    This License constitutes the entire agreement between you and SLG with respect to the Software and supersedes all prior or contemporaneous understandings regarding such subject matter. No amendment to or modification of this License will be binding unless made in writing and signed by SLG.  No failure to exercise, and no delay in exercising, on the part of either party, any right or any power hereunder shall operate as a waiver thereof, nor shall any single or partial exercise of any right or power hereunder preclude further exercise of any other right hereunder.  In the event of a conflict between this License and any applicable purchase or other terms, the terms of this License shall govern.</p>
				</div>
			</div>
		</article>
	</div>
</section>
      </div>
    </section>
  )
}