/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ResetpasswordLazyImport = createFileRoute('/resetpassword')()
const RegisterLazyImport = createFileRoute('/register')()
const LogoutLazyImport = createFileRoute('/logout')()
const LoginLazyImport = createFileRoute('/login')()
const JobsLazyImport = createFileRoute('/jobs')()
const ForgotLazyImport = createFileRoute('/forgot')()
const ContactLazyImport = createFileRoute('/contact')()
const CloudhostingLazyImport = createFileRoute('/cloudhosting')()
const AccountLazyImport = createFileRoute('/account')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ResetpasswordLazyRoute = ResetpasswordLazyImport.update({
  path: '/resetpassword',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/resetpassword.lazy').then((d) => d.Route))

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const LogoutLazyRoute = LogoutLazyImport.update({
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const JobsLazyRoute = JobsLazyImport.update({
  path: '/jobs',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/jobs.lazy').then((d) => d.Route))

const ForgotLazyRoute = ForgotLazyImport.update({
  path: '/forgot',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/forgot.lazy').then((d) => d.Route))

const ContactLazyRoute = ContactLazyImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))

const CloudhostingLazyRoute = CloudhostingLazyImport.update({
  path: '/cloudhosting',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cloudhosting.lazy').then((d) => d.Route))

const AccountLazyRoute = AccountLazyImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      preLoaderRoute: typeof AccountLazyImport
      parentRoute: typeof rootRoute
    }
    '/cloudhosting': {
      preLoaderRoute: typeof CloudhostingLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/forgot': {
      preLoaderRoute: typeof ForgotLazyImport
      parentRoute: typeof rootRoute
    }
    '/jobs': {
      preLoaderRoute: typeof JobsLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      preLoaderRoute: typeof LogoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/resetpassword': {
      preLoaderRoute: typeof ResetpasswordLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AccountLazyRoute,
  CloudhostingLazyRoute,
  ContactLazyRoute,
  ForgotLazyRoute,
  JobsLazyRoute,
  LoginLazyRoute,
  LogoutLazyRoute,
  RegisterLazyRoute,
  ResetpasswordLazyRoute,
])

/* prettier-ignore-end */
